### ISSUE TITLE
coffee dependency not specified

### ISSUE THREAD

**Issue by artifex404** [triggercode/mamp-cli#1]
<img width="496" alt="screen shot 2016-01-28 at 23 04 43" src="https://cloud.githubusercontent.com/assets/3011068/12658741/8b6f9f90-c613-11e5-9b0b-feb4179431ce.png">

**Comment by toovy** [comment]
Hi artifex,
thanks for your feedback. As stated in the readme the global coffee-script installation **was** **needed** (npm install -g coffee-script). But I've pushed a **new version (0.0.5)** that uses coffee-script as local dependency. Could you please try to install with

```
$ npm install -g maml-cli@0.0.5
```

Then it should work. Feel free to reopen if not!

BR, toovy
