### ISSUE TITLE
Feature request: switch to path instead of favorite

### ISSUE THREAD

**Issue by calebgrove** [triggercode/mamp-cli#5]
It would be really handy if we could switch directly to a directory instead of having to add every path we want to use as a favorite. For example:

    mamp switch /path/to/webroot/directory

**Comment by toovy** [comment]
@CalebGrove thanks for the request. I've pushed two new versions, one with the new command `mamp cwd` that uses your current working directory as DocumentRoot and one with the possibility to pass a path to switch (just as you requested).
