### ISSUE TITLE
Feature Request: NGINX

### ISSUE THREAD

**Issue by itsmelion** [triggercode/mamp-cli#8]
Shalom!

I see mamp-cli does nothing on my computer. say its started but its not functional. maybe because its Nginx by default?

Environment | Version
------------ | -------------
OS | OSX
Node | 9.2.0
NPM | 5.6.0
MAMP | 4.2 using NGINX
mySQL | 5.6.35
php | 7.1.7

**Comment by toovy** [comment]
Hi @itsmelion,
sorry for the late reply. I'm pretty sure NGINX is the reason, was the package modifies the httpd.conf from Apache. So that would be a new feature. As my company completely moved to a docker-based development solution, I would appreciate any pull request.
Thanks, BR, toovy
